name: BanList
main: com.gmail.bwinkl04.BanList
version: 1.1
commands:
   BanList:
      description: Shows a list of banned players.
      usage: /banlist
      permission: banlist.banlist
      permission-message: You don't have permission to see the BanList.